import { MapLayerConfig } from "../types/isie";

export const DEFAULT_MAP_LAYERS: MapLayerConfig[] = [
  {
    id: "layer-red-zones",
    name: "Hazard Red Zones (Module 01)",
    category: "HAZARD_ZONES",
    description: "Unavailable: no authoritative or workspace-backed hazard-zone layer is configured.",
    enabled: false,
    opacity: 0.85,
    sourceProvider: "Not connected",
    latencySpec: "Unavailable",
  },
  {
    id: "layer-sentinel1-sar",
    name: "Copernicus Sentinel-1 SAR",
    category: "SATELLITE",
    description: "Synthetic Aperture Radar for cloud-penetrating waterbody & flood extent mapping",
    enabled: false,
    opacity: 0.65,
    sourceProvider: "Copernicus Open Access Hub",
    latencySpec: "Not connected",
  },
  {
    id: "layer-sentinel2-optical",
    name: "Sentinel-2 Multi-Spectral Optical",
    category: "SATELLITE",
    description: "High-resolution optical imagery for vegetation, terrain, and habitation change detection",
    enabled: false,
    opacity: 0.7,
    sourceProvider: "ESA / Copernicus",
    latencySpec: "Not connected",
  },
  {
    id: "layer-cwc-hydrology",
    name: "CWC River & Gauge Telemetry",
    category: "HYDROLOGICAL",
    description: "Central Water Commission automated river level telemetry & danger mark thresholds",
    enabled: false,
    opacity: 0.9,
    sourceProvider: "Central Water Commission",
    latencySpec: "Not connected",
  },
  {
    id: "layer-imd-radar",
    name: "IMD Doppler Radar & Precipitation",
    category: "HYDROLOGICAL",
    description: "India Meteorological Department live Doppler weather radar & extreme rainfall vectors",
    enabled: false,
    opacity: 0.6,
    sourceProvider: "India Meteorological Department",
    latencySpec: "Not connected",
  },
  {
    id: "layer-carrying-capacity",
    name: "Carrying Capacity & Relocation Shelters (Module 02 & 03)",
    category: "INFRASTRUCTURE",
    description: "Shelter occupancy, hospital bed availability, emergency reserves, and evacuation bottlenecks",
    enabled: false,
    opacity: 0.8,
    sourceProvider: "District Disaster Control Room Network",
    latencySpec: "Not connected",
  },
  {
    id: "layer-evacuation-corridors",
    name: "Critical Evacuation Corridors & Road Cutoffs",
    category: "INFRASTRUCTURE",
    description: "OpenStreetMap primary routes, bridge structural alerts, and severed arterial roads",
    enabled: false,
    opacity: 0.75,
    sourceProvider: "OSM / State Highway Telemetry",
    latencySpec: "Not connected",
  },
  {
    id: "layer-population-density",
    name: "Census Habitation & Vulnerability Density",
    category: "POPULATION",
    description: "Gridded population of India, high-vulnerability habitations, elderly & child demographic ratios",
    enabled: false,
    opacity: 0.5,
    sourceProvider: "Survey of India / Census Geodatabase",
    latencySpec: "Not connected",
  },
];

export const AUTHORITATIVE_SOURCES = [
  {
    id: "imd",
    code: "IMD-GOV-IN",
    name: "India Meteorological Department (IMD)",
    type: "Meteorological & Radar",
    endpointCategory: "National Agency API",
    status: "STANDBY_UNCONNECTED",
    description: "Doppler radar, gridded precipitation, cyclone track forecasts, severe weather alerts.",
    referenceUrl: "https://mausam.imd.gov.in/",
  },
  {
    id: "cwc",
    code: "CWC-GOV-IN",
    name: "Central Water Commission (CWC)",
    type: "Hydrological & River Gauge",
    endpointCategory: "National Basin Telemetry",
    status: "STANDBY_UNCONNECTED",
    description: "River gauge stages, flood warning levels, dam discharge rates, reservoir capacity.",
    referenceUrl: "https://cwc.gov.in/",
  },
  {
    id: "isro-nrsc",
    code: "ISRO-NDEM",
    name: "ISRO / NRSC NDEM",
    type: "National Geospatial Disaster Management",
    endpointCategory: "Earth Observation Portal",
    status: "STANDBY_UNCONNECTED",
    description: "Satellite disaster mapping, flood inundation layers, landslide susceptibility atlas.",
    referenceUrl: "https://www.isro.gov.in/DBEM.html",
  },
  {
    id: "copernicus",
    code: "ESA-COPERNICUS",
    name: "Copernicus Data Space Ecosystem",
    type: "Spaceborne SAR & Optical",
    endpointCategory: "International Earth Observation",
    status: "STANDBY_UNCONNECTED",
    description: "Sentinel-1 SAR interferometry for water extent, Sentinel-2 10m multispectral imagery.",
    referenceUrl: "https://dataspace.copernicus.eu/",
  },
  {
    id: "nasa-firms",
    code: "NASA-FIRMS",
    name: "NASA FIRMS",
    type: "Thermal & Fire Radiometry",
    endpointCategory: "Global Near-Real-Time",
    status: "STANDBY_UNCONNECTED",
    description: "MODIS / VIIRS active fire detections and high-temperature industrial/hazard thermal anomalies.",
    referenceUrl: "https://firms.modaps.eosdis.nasa.gov/",
  },
  {
    id: "osm",
    code: "OSM-GEODATA",
    name: "OpenStreetMap Geographic Infrastructure",
    type: "Road & Topological Network",
    endpointCategory: "Open Geospatial Database",
    status: "STANDBY_UNCONNECTED",
    description: "Road networks, bridge locations, health facilities, schools, and shelter infrastructure.",
    referenceUrl: "https://www.openstreetmap.org/",
  },
];
